---
exclude: docs|node_modules|migrations|.git|.tox|.mypy_cache|frontend
default_stages: [commit]
fail_fast: true

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: requirements-txt-fixer
          - id: check-merge-conflict
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3 # or other specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
      rev: v0.4.10
      hooks:
      # Run the linter.
          - id: ruff
            args: [--fix]
      # Run the formatter.
          - id: ruff-format
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.9
      hooks:
          - id: bandit
